### ISSUE TITLE
Make a figure to illustrate the SV evaluation approach

### ISSUE THREAD

**Issue by jmonlong** [jmonlong/manu-vgsv#68]

**Comment by jmonlong** [comment]
I tweaked a bit the cartoon I used for the package page. I'll add that as a supplementary figure and point at it in the methods.

![sveval-cartoon](https://user-images.githubusercontent.com/5704457/57548724-8dfaa800-7316-11e9-837d-3f615faeed2f.jpg)

**Comment by glennhickey** [comment]
Cool!  No reason to not move a lot of this work you'd already done
describing sveval into the supplement.  It'll probably be the most
impactful part of the paper!
