### ISSUE TITLE
Add Acknowledgments, Competing Interests etc.

### ISSUE THREAD

**Issue by jonassibbesen** [jmonlong/manu-vgsv#88]
I created this issue so that we don't forget it. I could not find it mentioned anywhere.

**Comment by jmonlong** [comment]
Good point, I added a draft of this section in #91. Please review and add competing interest/funding or other thigs I might have forgot.

**Comment by glennhickey** [comment]
@benedictpaten Can you please fill out the funding info as needed for UCSC people (ie me?) here:
https://github.com/jmonlong/manu-vgsv/blob/master/content/059.declarations.md

@ekg Do you have something you want to mention funding-wise?

Same for all other authors? @adamnovak @jeizenga @edawson @jonassibbesen @jltsiren

**Comment by jeizenga** [comment]
Done, just pushed it straight to master.

**Comment by adamnovak** [comment]
I also added myself, and the grant numbers I have been carrying around
from paper to paper. I suspect these also apply to a bunch of other
people.

**Comment by jmonlong** [comment]
I added the funding for UCSC/Benedict that I got from Mary.

@ekg @edawson anything you want to add in #99 ?

**Comment by eldariont** [comment]
PR #99 was merged so I guess this issue can be closed, @jmonlong?

**Comment by jonassibbesen** [comment]
Updated my funding slightly. Realized I do not need to write grant number. Pushed it straight to master.
